### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Michael21107** [Flohhhhh/ultimate-lighting-controller#26]
add to the license some info about redistributing the plugin **edited** (like if one needs to state his changes)

**Comment by Flohhhhh** [comment]
https://github.com/Flohhhhh/ultimate-lighting-controller/blob/main/LICENSE.md

**Comment by Michael21107** [comment]
I meant specifically what someone needs to do if he makes some changes and wants to distribute it (like paid or free update or overhaul), eg. state the changes he made to the code

**Comment by Flohhhhh** [comment]
I updated after closing this to be more comprehensive 

Including:

> Permission is hereby granted, free of charge, to any person obtaining a copy of this resource and associated documentation files (the "Resource"), to deal in the Resource without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Resource, subject to the following conditions:

**Comment by Michael21107** [comment]
yep, nice
