### ISSUE TITLE
ULC ERROR

### ISSUE THREAD

**Issue by Enjoy1982** [Flohhhhh/ultimate-lighting-controller#5]
Hi sorry bur somebody can help me whit the script?? i have a error: 

[          script:ulc] [ULC] Checking for external vehicle resources.
[          script:ulc] [ULC WARNING] A config in "Cars" uses Stage Buttons, but HUD/UI is globally disabled. This is not recommended for user experience.
[          script:ulc] [ULC] Loaded external configuration for "dinghy"
[          script:ulc] [ULC] Loaded external configuration for "dodgesamu"
[          script:ulc] [ULC] Loaded external configuration for "ghispo2"
[          script:ulc] [ULC] Loaded external configuration for "police"
[          script:ulc] [ULC] Loaded external configuration for "police2"
[          script:ulc] [ULC] Loaded external configuration for "police3"
[          script:ulc] [ULC] Loaded external configuration for "policeb"
[          script:ulc] [ULC] Loaded external configuration for "policeinsurgent"
[          script:ulc] [ULC] Loaded external configuration for "policet"
[          script:ulc] [ULC] Loaded external configuration for "riot"
[          script:ulc] [ULC] Loaded external configuration for "polmav"
[          script:ulc] [ULC] Loaded external configuration for "survivor"
[          script:ulc] [ULC WARNING] A config in "Cars" uses Stage Buttons, but HUD/UI is globally disabled. This is not recommended for user experience.
[          script:ulc] [ULC] Loaded external configuration for "pdram"
[          script:ulc] [ULC] Done loading external vehicle resources.
[          script:ulc] [ULC] Loaded: dinghy
[          script:ulc] [ULC] Loaded: dodgesamu
[          script:ulc] [ULC] Loaded: ghispo2
[          script:ulc] [ULC] Loaded: police
[          script:ulc] [ULC] Loaded: police2
[          script:ulc] [ULC] Loaded: police3
[          script:ulc] [ULC] Loaded: policeb
[          script:ulc] [ULC] Loaded: policeinsurgent
[          script:ulc] [ULC] Loaded: policet
[          script:ulc] [ULC] Loaded: riot
[          script:ulc] [ULC] Loaded: polmav
[          script:ulc] [ULC] Loaded: survivor
[          script:ulc] [ULC] Loaded: pdram

[          script:ulc] Error: Request Failed.
[          script:ulc] Status Code: 504

**Comment by Flohhhhh** [comment]
This is the only relevant warning
```
[ULC WARNING] A config in "Cars" uses Stage Buttons, but HUD/UI is globally disabled. This is not recommended for user experience.
```
You have set the HUD to be disabled but use stage buttons on vehicles which will make it difficult for users to use the buttons.

This is safe to ignore:
```
[ script:ulc] Error: Request Failed.
[ script:ulc] Status Code: 504
```

**Comment by Enjoy1982** [comment]
ok thanks to much i will go to discord also
